### ISSUE TITLE
Blank page when going to http://localhost:8080/ after following "Up and Running" instructions

### ISSUE THREAD

**Issue by jeffslofish** [FarmBot/farmbot-web-frontend#113]
I followed the "Up and Running" instructions, and when I go to http://localhost:8080/ I get a blank page. However, I did notice that if I go to http://localhost:8080/app/login then I do get a login page, so I guess my setup isn't completely broken.

**Comment by ConnorRigby** [comment]
The documentation isn't proper.  http://localhost:8080/app/login is the correct URL. We will update the README.md shortly.

**Comment by RickCarlino** [comment]
@jeffslofish Hi Jeff, Thanks for pointing this one out!

It looks like the docs were indeed a few weeks behind. I've updated the docs. I appreciate your help in keeping the docs current.
