### ISSUE TITLE
Farm Designer issues 

### ISSUE THREAD

**Issue by mrmadhu** [FarmBot/farmbot-web-frontend#136]
1) there is no result while searching plants, search shows only potato but no images when adding to canvas 
2) Canvas is not complete (attaching screenshot)
3) Group option does not work, no search result 
4) nothing happening in events 

![image](https://cloud.githubusercontent.com/assets/22852245/19688141/05d8abbc-9ae6-11e6-907b-5f4e99387250.png)

**Comment by RickCarlino** [comment]
The Farm Designer is not finished nor is it ready for use. We're tracking the issues above and have them as our next target after we finish things up on the sequences page.

Events are working on the device side, but the UI you see is just a mockup for now. That's on the calendar this week and next week.

Groups are a very early concept that we have not yet finished. Start date on that is TBD.

In the future, please raise one issue per problem found.
