### ISSUE TITLE
Need to reload staging.farmbot.io, every time after the RPI reboot 

### ISSUE THREAD

**Issue by mrmadhu** [FarmBot/farmbot-web-frontend#137]
Need to reload staging.farmbot.io, every time after the RPI reboot

**Comment by RickCarlino** [comment]
Can you please give more details? Why do you need to reload the RPI? Do you see any errors or messages in the Javascript console (`ctrl + shift + j` in Chrome).

**Comment by mrmadhu** [comment]
sorry looks fine now, may be a local issue, till now i was reloading staging.farmbot.io to detect the online RPI. you can close the issue

**Comment by RickCarlino** [comment]
Great. Thanks.
