### ISSUE TITLE
Hardware settings wont show up

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/farmbot-web-frontend#142]
Hello everyone,

I'm having trouble with the settings since 2.1.0.
The values seem to get saved if I write new ones in and press "Save", but right after that they disappear and "---" is shown in every cell. But Motors move in the speed that I saved.
I already flashed a new Image but still the same thing.

![image](https://cloud.githubusercontent.com/assets/23129562/19824840/5e120b7c-9d73-11e6-9078-883bcc80ea69.png)

**Comment by roryaronson** [comment]
Hey thanks for chiming in! This is known issue and it should be resolved on Monday with a new production deploy.

**Comment by AscendFB** [comment]
Hey, just wanted to let you know that changing any setting does not work for me yet. After updating to 2.1.2 there are default values entered and those cannot be saved. Is this already known?

**Comment by ConnorRigby** [comment]
@AscendFB, I believe that is because http://my.farmbot.io cant use the device hardware yet. 
if you reset your bot and sign into http://staging.farmbot.io (you'll have to create an account first) it should work just fine.

**Comment by AscendFB** [comment]
@ConnorRigby Oh, excuse me, I was already using http://staging.farmbot.io/ this time, I didnt even try my.farmbot.io. Guess I could try it with my.farmbot.io again instead of staging.
Btw, should that "Steps per mm" box work already?

**Comment by ConnorRigby** [comment]
can i see a screenshot of what your looking at?
steps per mm should be populated with 500 by default.

**Comment by AscendFB** [comment]
![image](https://cloud.githubusercontent.com/assets/23129562/19981550/b0afcc32-a202-11e6-9d14-574defa16a42.png)


I feel like there is no difference in movement if I change the "steps per mm" value.
All axes are moving, but even if I change the Speed to f.e. 100, it still moves like 1500 which is too fast for my current setup.

**Comment by ConnorRigby** [comment]
yeah so unfortunately although it is being set in farmbot OS, our [Arduino Firmware](https://github.com/FarmBot/farmbot-arduino-firmware/tree/v0.0.1) doesnt support speed quite yet.

**Comment by RickCarlino** [comment]
Closing this issue since it is not directly related to the frontend.
