### ISSUE TITLE
web app login credential should have an option to save

### ISSUE THREAD

**Issue by mrmadhu** [FarmBot/farmbot-web-frontend#144]
web app does not save the login credential information, is it intentional or yet to implement functionality ? 

Madhu

**Comment by RickCarlino** [comment]
## Staying Logged In

1. Log in from `/app/login`.
2. Close the tab and visit `/app/dashboard/controls`.
3. You should still be logged in for 30 days, unless you have `localStorage` disabled.

## Logging Out

Click the `logout` button on the navbar or visit the login page again.

Eventually, we are going to add a "stay logged in" check box and refactor this down further, but this gets the job done for now.

Please let me know if that doesn't work for you- it works fine for us. I will add a popup message on the login page to let users know they have been logged out when visiting the login page.

**Comment by mrmadhu** [comment]
i end up login every time i access staging.farmbot.io

**Comment by roryaronson** [comment]
Yea @rickcarlino I think this is pretty confusing right now. I think most people always navigate to the root domain of the app which is the splash page, which then goes to the login page, which automatically signs people out.

I think the trello card for the unified login page should resolve this issue.

Thanks for the feedback @mrmadhu, we'll get this worked out so it behaves more like other web apps.
