### ISSUE TITLE
See the wrong camera images

### ISSUE THREAD

**Issue by fluffy** [FarmBot/farmbot-web-frontend#163]
# Expected Behavior

I don't have a camera attached to mine yet so I would expect to see black when I go to https://my.farmbot.io/app/controls

# Actual Behavior

I'm seeing images from some other person's camera. 

# Steps to Reproduce

Go to https://my.farmbot.io/app/controls

**Comment by RickCarlino** [comment]
@fluffy That's our FarmBot! We put that there as a default so people can see what we're up to if they haven't set a camera feed of their own.

If you would like a camera feed of your own, you can use any camera software that supports HTTP streaming. We haven't don't much integration for camera feeds yet, unfortunately.

**Comment by fluffy** [comment]
Oh, cool - thank you for the info.

**Comment by RickCarlino** [comment]
No problem! Best of luck with device setup.
