### ISSUE TITLE
Can not enter absolute position in controls

### ISSUE THREAD

**Issue by fluffy** [FarmBot/farmbot-web-frontend#164]
# Expected Behavior

The https://my.farmbot.io/app/controls has place to enter x,y,z position and hit GO. 

# Actual Behavior

When I try and enter a number in one of the axis boxes, I can not type anything or it is instantly changed back to the previous value. 

# Steps to Reproduce

**Comment by MrChristofferson** [comment]
@fluffy Thanks for the catch! We'll take a look. For now, if you highlight the entire value within the input, then attempt to change it, it should work. Let us know if you run into any more issues.

**Comment by fluffy** [comment]
This seems fixed. Thanks. Still some weirdness. If I refresh the page, and enter just a value in the x box, when I hit go, instead of leaving the Y and Z where they are, it is as if I entered 0 in both of them and it moves the robot to 0,0 on y and z (as well as whatever I entered on x. But it's usable now as soon as you get used to this.
