### ISSUE TITLE
i18next for localization ru

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot-web-frontend#166]
Could you tell me how to work with i18next?

**Comment by RickCarlino** [comment]
Hi @Daniil145 . Here's how it works:

1. Clone and fork this repository.  Follow the usual [setup instructions](https://github.com/FarmBot/farmbot-web-frontend#developer-setup)
2. Look through the project for `*.tsx` files. Find places where we call `t()`. Example: Line 13 of `/src/regimens/bulk_scheduler/add_button.tsx` calls `t("add")`.
3. When you find a phrase you want to translate, open the `*.js` translation file for your language (example: `/public/app-resources/languages/ru.js`) and add an entry for the phrase "add". I have added a few examples to `ru.js`. If you do a global search of the project for the phrase `from "i18next"` you can easily find all the places that require translation.
4. Continue this process for all the phrases in the application you wish to translate.
5. Submit a pull request with your proposed translations.

When you are submitting translations, please try to not make changes to files other than the translation file (`/public/app-resources/languages/ru.js`). If you do need to make changes to the codebase

**Comment by RickCarlino** [comment]
@Daniil145 Also, I would like to mention that if you do write a translation, you will be the first user to do so. If you hit any issues during the translation process (very possible) please let me know. We are at a very early stage with `i18n` on this project.
