### ISSUE TITLE
It doesn't move in mm

### ISSUE THREAD

**Issue by rorycan** [FarmBot/farmbot-web-frontend#167]
When I tell it to move using the control panel to 100 mm, it moves around 20 mm.

**Comment by RickCarlino** [comment]
@rorycan We're aware of this issue and working on it today. More details coming soon.

**Comment by fluffy** [comment]
Not sure what the plan for this is but my preference would be the G00 codes are sent in mm to the Arduino and it moves them to steps.

**Comment by RickCarlino** [comment]
@fluffy The plan was to perform the conversion on the Pi side of things, although we got side tracked on some issues in the configurator this week. Could you elaborate a bit more on your thinking behind that preference?

**Comment by fluffy** [comment]
Well the nice part about G codes in mm is that is supported by pretty much everything that generates or consumes G codes and we could take the G codes and feed them into simulator for a CNC machine and preview what will happen. It also means that any custom configurations mapping the number of steps per mm can be stored in the eeprom on Arduino. This seems like a nice place for it where it will stay tied to the hardware it was built for and won't get wiped by flashing new software onto the Arduino or PI. It's also what pretty much every 3D printer or CNC machine that uses a similar architecture does. It just seems natural to form a nice isolation between the Arduino needing to know the details of the hardware configuration and the rest of the system not needing to worry about that.

**Comment by fluffy** [comment]
This is fixed in latest stuff. Should I just close this ?
