### ISSUE TITLE
Sometimes it randomly resets to 0,0,0

### ISSUE THREAD

**Issue by rorycan** [FarmBot/farmbot-web-frontend#168]
We were moving it around, and sometimes it resets to thinking it's at 0,0,0. The next absolute move results in it crashing.

**Comment by RickCarlino** [comment]
@rorycan @fluffy Has this one shown up after the last release? We've made quite a few updates to the firmware since 2 JAN.

**Comment by mdingena** [comment]
Yes, this is still happening. I'm running `farmbot-rpi3-3.1.4.img`

**Comment by fluffy** [comment]
I'm trying to upgrade and retest but have not got there yet. I have a random untested hypothesis on what might be happening ... the PI close and opens the serial port to the Arduino, this would cause the Arduino to reset  which would reset the position to 0.

**Comment by ConnorRigby** [comment]
I _think_ i know what is happening here. @fluffy is spot on actually.
