### ISSUE TITLE
The Z axis doesn't always calibrate precisely 

### ISSUE THREAD

**Issue by rorycan** [FarmBot/farmbot-web-frontend#170]
We calibrate the Z axis, and when we move it down, it isn't always at the same position.

**Comment by roryaronson** [comment]
This might be an issue with [backlash](https://en.wikipedia.org/wiki/Backlash_(engineering)) in the hardware. How far off is it? Is the problem compounding or is it always off by the same amount?

**Comment by fluffy** [comment]
We need to go measure this but just randomly guessing to probably be in the 5 mm range and seem. I have not checked if it is consistent if we are always moving *up*. It did seems like it was probably coming from the flex coupling stretching and compressing.  We will play some more with it this weekend.

**Comment by fluffy** [comment]
I think what was happening before is did not have enough friction in the Z system and we when the "enable" was turned off to the z stepper motor, the screw would actually turn about 1/3 of a turn significantly changing the position. Adjusting the screw block a bit introduced enough friction to have this not happen. After that, when we went and did some measurements, this seemed to be working. If we we calibrate then move just down, we get to a repeatability around about +/- .25 mm. But if we then move down then up, it we are getting close to .5 mm of backlash but it is pretty consistent. We can actually see the flex coupling stretching from up to down direction but even with this .5 mm it seems like we can place and pick up tools. We are really jus starting on the programming for that so not sure but looks like it should work.

**Comment by fluffy** [comment]
The new stuff that keeps the z axis enabled seems to have fixed this. I think we can close this one. Thanks.
