### ISSUE TITLE
Issue when running ./install_frontend.sh

### ISSUE THREAD

**Issue by pablomat** [FarmBot/farmbot-web-frontend#174]
After running the script i get the following error, the webserver is responding though.

ERROR in /tmp/farmbot_frontend/node_modules/@types/snapsvg/index.d.ts
(57,16): error TS2323: Cannot redeclare exported variable 'filter'.

ERROR in /tmp/farmbot_frontend/node_modules/@types/snapsvg/index.d.ts
(58,16): error TS2323: Cannot redeclare exported variable 'path'.

ERROR in /tmp/farmbot_frontend/typings/snapsvg.d.ts
(57,16): error TS2323: Cannot redeclare exported variable 'filter'.

ERROR in /tmp/farmbot_frontend/typings/snapsvg.d.ts
(58,16): error TS2323: Cannot redeclare exported variable 'path'.
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ./~/css-loader!./~/react-select/dist/react-select.css 7.01 kB {0} [built]
       [2] ./~/css-loader!./~/sass-loader!./src/css/_index.scss 36.3 kB {0} [built]

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! farmbot-web-frontend@1.1.0 build: `node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the farmbot-web-frontend@1.1.0 build script 'node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the farmbot-web-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs farmbot-web-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls farmbot-web-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/farmbot_frontend/npm-debug.log

[npm-debug.log.txt](https://github.com/FarmBot/farmbot-web-frontend/files/731196/npm-debug.log.txt)

**Comment by RickCarlino** [comment]
@pablomat Interesting. I will take a look in a moment. This might be a local settings issue, because we just ran this script on a Heroku instance 20 minutes ago. I will let you know if I find anything.

**Comment by RickCarlino** [comment]
@pablomat Can you try running these commands one-at-a-time and see if you get any new errrors?

```
CURRENT_DIR=$(pwd)
rm -rf /tmp/farmbot_frontend
mkdir /tmp/farmbot_frontend
git clone https://github.com/farmbot/farmbot-web-frontend.git /tmp/farmbot_frontend
cd /tmp/farmbot_frontend
npm install
chmod +x node_modules/webpack/bin/webpack.js
npm run build
cd $CURRENT_DIR
mkdir public/ -p
cp -R /tmp/farmbot_frontend/public/* public/
```

**Comment by pablomat** [comment]
Hi Rick, 

I've tried what you suggested and it's giving me the same error, I've put everything into a log. Thanks 
[Output.txt](https://github.com/FarmBot/farmbot-web-frontend/files/732718/Output.txt)

**Comment by RickCarlino** [comment]
@pablomat Have you checked to see if those errors are causing any issues on the app? It looks like there are just some type errors from `snapSVG` which might not actually stop you from running the app. It might just be some some issues related to (unstable) work we're doing on the Farm Designer right now.

**Comment by pablomat** [comment]
Hi, 

Well it's hard to tell but i doubt that it's causing the issues that i have at the moment, the webserver is reachable but i cannot create a user as i receive the message "Possible connectivity issues..".

mqtt and web api are running, i can open another issue for this in the proper section

**Comment by RickCarlino** [comment]
@pablomat The warnings have been removed from the latest version. They should be gone if you run `./install_frontend.sh` again.

**Comment by pablomat** [comment]
Hi, indeed they're gone now. Thanks

**Comment by punit121** [comment]
@RickCarlino i'm getting following warning while running ./install_frontend.sh

npm WARN deprecated @types/redux-thunk@2.1.0: This is a stub types definition for Redux Thunk (https://github.com/gaearon/redux-thunk). Redux Thunk provides its own type definitions, so you don't need @types/redux-thunk installed!
npm WARN deprecated yarn@0.23.4: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install

**Comment by punit121** [comment]
@RickCarlino Also i'm getting the following error 


> farmbot-web-frontend@1.1.0 build C:\Users\hp\AppData\Local\Temp\farmbot_frontend
> node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! farmbot-web-frontend@1.1.0 build: `node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the farmbot-web-frontend@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2017-05-16T11_47_59_684Z-debug.log

**Comment by RickCarlino** [comment]
@punit121 I'm not sure that `./install_frontend.sh` is going to work on Windows.
I've heard Windows recently added the ability to run shell scripts, but I don't have a Windows machine to test off of. My guess is that this:

```
'node_modules' is not recognized as an internal or external command,
```

happens because this:

```
node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details
```

Uses Unix style `/` delimiters instead of windows style `\` delimiters. I am not certain of this though.

**Comment by punit121** [comment]
@RickCarlino What best i can do  to setup **Farmbot-Web-Api** on windows  , as i am getting lots of error in each step of config.
