### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by vindekator** [FarmBot/farmbot-web-frontend#177]
# Expected Behavior
Running step 3. bundle install

# Actual Behavior
git clone https://github.com/FarmBot/Farmbot-Web-API farmbot-web-app
Cloning into 'farmbot-web-app'...
remote: Counting objects: 13611, done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 13611 (delta 63), reused 0 (delta 0), pack-reused 13475
Receiving objects: 100% (13611/13611), 7.80 MiB | 10.10 MiB/s, done.
Resolving deltas: 100% (8290/8290), done.
Checking connectivity... done.
dadoo@farmhost:~$ cd farmbot-web-app
dadoo@farmhost:~/farmbot-web-app$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/fog/fog-google
Fetching https://github.com/RickCarlino/smarf_doc.git
Installing rake 11.3.0
Installing concurrent-ruby 1.0.2
Using i18n 0.7.0
Installing minitest 5.9.1
Using thread_safe 0.3.5
Installing builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Installing bcrypt 3.1.11 with native extensions
Installing choice 0.2.0
Installing climate_control 0.1.0
Installing coderay 1.1.1
Installing daemons 1.2.4
Installing database_cleaner 1.5.3
Installing orm_adapter 0.5.0
Using method_source 0.8.2
Using thor 0.19.4
Installing diff-lcs 1.2.5
Installing docile 1.1.5
Installing unf_ext 0.0.7.2 with native extensions
Installing eventmachine 1.2.1 with native extensions
Installing excon 0.54.0
Installing formatador 0.2.5
Installing multi_json 1.12.1
Installing ice_cube 0.14.0
Using json 1.8.3
Installing jwt 1.5.6
Installing mimemagic 0.3.2
Installing netrc 0.11.0
Installing pg 0.19.0 with native extensions
Installing slop 3.6.0
Installing rack-cors 0.4.0
Using bundler 1.14.3
Installing ruby-graphviz 1.2.2
Installing rails_serve_static_assets 0.0.5
Installing rails_stdout_logging 0.0.5
Installing rspec-support 3.5.0
Installing simplecov-html 0.10.0
Using smarf_doc 1.0.0 from https://github.com/RickCarlino/smarf_doc.git (at master@40dc733)
Installing faker 1.6.6
Using tzinfo 1.2.2
Installing nokogiri 1.6.8.1 with native extensions
Using rack-test 0.6.3
Installing warden 1.2.6
Installing rack-attack 5.0.1
Installing sprockets 3.7.0
Installing websocket-driver 0.6.4 with native extensions
Using mime-types 3.1
Installing cocaine 0.5.8
Installing figaro 1.1.1
Installing unf 0.1.4
Installing thin 1.7.0 with native extensions
Installing fog-core 1.43.0
Installing rollbar 2.13.3
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

# Steps to Reproduce

[mkmf.log.txt](https://github.com/FarmBot/farmbot-web-frontend/files/737256/mkmf.log.txt)
[gem_make.out.txt](https://github.com/FarmBot/farmbot-web-frontend/files/737257/gem_make.out.txt)

**Comment by RickCarlino** [comment]
You're missing a local C library most likely. Can you try this?  http://stackoverflow.com/a/6040822/1064917 Please let me know if that fixes it

**Comment by vindekator** [comment]
Thank you very much.  That seems to have done the trick.

**Comment by vindekator** [comment]
I walked away for awhile.  Wasn't expecting such a quick response.  Very nice!

**Comment by RickCarlino** [comment]
No problem! ☺️
