### ISSUE TITLE
X value overwriting y value in  sequence rules

### ISSUE THREAD

**Issue by fluffy** [FarmBot/farmbot-web-frontend#183]
If I write an couple absolute move that do not import a location, save the sequence, then reload the page, the values for the y are replaced with the value that was in the y.

**Comment by roryaronson** [comment]
I don't quite understand the error. Can you outline how to recreate this in a

1. Step 1
2. Step 2
3. Kind of way?

**Comment by RickCarlino** [comment]
@fluffy I've seen this one come up in the past. It's related to the `key=` attribute on JSX elements.

We did a fix for this a week or two ago that seemed to clear it up. Are you running on a local server installation or on one of the official servers? My suspicion is that the production servers (my.farmbot.io - last updated Jan 19) are not running the version with the fix. One way to check would be to try it on the [staging server](https://staging.farmbot.io) and see if you can reproduce there.

**Comment by fluffy** [comment]
I'm having a bit of a problem on staging server, it wants to to verify email first but to do that it wants me to accept new TOS first, but to do that it wants me to verify email .... Can you just add me on staging server and I accept the new TOS. 

To answer questions on how to reproduce 

1. Create a sequence with more than one absolute move 
2. Make sure the x and y are different for each more
3. Save the sequence 
4. Reload the web page 
5. load the sequence 
6. at this point, the y values will be set to the x values and not the original ones

**Comment by RickCarlino** [comment]
@fluffy strange, I just registered for an account no problem. Perhaps it's related to the fact that our staging mail delivery is slow. Either way, I've manually verified your account if you would like to take a look now.

**Comment by fluffy** [comment]
thanks - I can log on staging now. I'm off on a work trip to San Fran this week so might be next weekend before I get a chance to play with it.

Sent with my thumbs. Sorry

**Comment by bdudout** [comment]
Hello,

I confirm there is still this issue, just add several absolute move to a sequence with different values for X Y and Z.
Click either save or save and run.
The movement for the farmbot will be correct according to the x y z you wrote. But the display is incorrect, the Y value is copied from X.

Tested on my.farmbot.io

**Comment by RickCarlino** [comment]
Fixed in latest release. Please let me know if you hit any issues.
