### ISSUE TITLE
Default move of 1000 mm in control leads to crashed 

### ISSUE THREAD

**Issue by fluffy** [FarmBot/farmbot-web-frontend#184]
If would be much nicer if the default was 10 mm. The page gets reloaded and I forget it has moved to 1000 mm. Then it crashes due to my bad. Then I get to enjoy the 20 minute calibration process :-)

**Comment by roryaronson** [comment]
Ah, yes good point. Before we had steps/mm implemented the default move amount of 1000 (steps) made sense. Now I think a default of 100 (mm) makes the most sense. 10 seems a little too small to me though unless you're working with a desktop-sized device. Would a 100mm default work for you or do you think 10 is better?

**Comment by fluffy** [comment]
100 mm sounds good. I just want to make it small enough that when I forget to click on what I want, it is not too likely to result in a crash.

**Comment by RickCarlino** [comment]
Sounds like this one is good to go for next release. Closing this issue. Feel free to discuss / reopen if you would like to keep the discussion going.
