### ISSUE TITLE
Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot-web-frontend#185]
./install_frontend.sh

> farmbot-web-frontend@1.1.0 build /tmp/farmbot_frontend
> node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details

module.js:327
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/farmbot_frontend/tools/webpack.config.prd.js:9:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/daniil145/.nvm/v4.4.5/bin/node" "/home/daniil145/.nvm/v4.4.5/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! farmbot-web-frontend@1.1.0 build: `node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the farmbot-web-frontend@1.1.0 build script 'node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details'.
npm ERR! This is most likely a problem with the farmbot-web-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs farmbot-web-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls farmbot-web-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/farmbot_frontend/npm-debug.log

[npm-debug.txt](https://github.com/FarmBot/farmbot-web-frontend/files/765189/npm-debug.txt)

**Comment by RickCarlino** [comment]
We're running `node v6.9.4`. I've never seen this error before, but I would guess it is related to your node version.

**Comment by Daniil145** [comment]
please change https://github.com/FarmBot/farmbot-web-frontend/blob/master/.nvmrc

**Comment by RickCarlino** [comment]
@Daniil145 I just checked the staging server: we are using `node 6.9.5`. It looks like that `nvm` file was being used by other developers who either stopped using NVM or no longer contribute to the project. We don't use it as part of our day-to-day, so I am going to remove it and add it to the `gitignore`

**Comment by Daniil145** [comment]
ok good it work!
may be you add version to readme?

**Comment by RickCarlino** [comment]
Sure thing. I will take care of it in the morning as I just stepped out for
the day. Glad your server is up and running.
