### ISSUE TITLE
Save & Run a sequence will always run the previous version of the sequence

### ISSUE THREAD

**Issue by bdudout** [FarmBot/farmbot-web-frontend#187]
Hello!

When updating a sequence, for example testing flashing lights 
write pin 8 1 
wait 250ms
write pin 8 0
wait 250 ms
etc

If I update the waiting value from 250ms to 1s and click save and run, it will always run the 250ms previous version of the sequence even is the 1s version is displayed

**Comment by RickCarlino** [comment]
@bdudout Interesting find. I will investigate this today.

**Comment by ConnorRigby** [comment]
@bdudout interesting. I believe this to be an OS level issue, and i have a suspect of what it is. Will get back to you soon!

**Comment by bdudout** [comment]
Great! tell me when it's good so that I can test again :)

**Comment by RickCarlino** [comment]
@bdudout This issue still needs some work on our end, but can be resolved by hitting the "sync" button before hitting "save and run". We will have a more elegant solution in future releases.
