### ISSUE TITLE
New account page problem with Firefox

### ISSUE THREAD

**Issue by SebastianoPistore** [FarmBot/farmbot-web-frontend#190]
The account creation page does not detect the check on Terms of use Agree using Firefox, but works on Chrome. Firefox ask to accept the Terms even if there is already tick.

# Expected Behavior
Chrome
![ok](https://cloud.githubusercontent.com/assets/15121240/23650550/c7ba232e-0322-11e7-95ef-6859ad64a344.jpg)

# Actual Behavior
Firefox
![err](https://cloud.githubusercontent.com/assets/15121240/23650379/30e72a64-0322-11e7-88bb-fc4771210a73.jpg)

**Comment by RickCarlino** [comment]
Thanks for the report, @SebastianoPistore . I was able to reproduce this problem on `Firefox 51.0.1 (64-bit)` and will investigate shortly and let you know what we find.
