### ISSUE TITLE
sequence problem

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot-web-frontend#191]
I set X=10 Y=0 Z=0 click save and result on screen
X=10 Y=10 Z=0
![screenshot_2017-03-09-21-11-22](https://cloud.githubusercontent.com/assets/20598279/23764029/03d94f4c-050d-11e7-8377-61d7907333ba.png)
# Expected Behavior

# Actual Behavior

# Steps to Reproduce

**Comment by RickCarlino** [comment]
@Daniil145 This was recently fixed but has not been deployed to production yet. You can try it out on `staging.farmbot.io` to verify.

**Comment by Daniil145** [comment]
Web fronted or api bug?

**Comment by RickCarlino** [comment]
@Daniil145 The fix was implemented on the frontend.

**Comment by Daniil145** [comment]
I update my fronted on you git. And i get this error. May be api?

**Comment by Daniil145** [comment]
or fix not available on github?

**Comment by RickCarlino** [comment]
@Daniil145 Did you pull down pull down from `FarmBot/farmbot-web-frontend master` and run `./install_frontend.sh`?

What do you see in your Javascript console for version information? This is what staging has:

```
eb2d528
Thu Mar 9 11:42:26 2017 -0700
fix-select
```

Is your version older or newer than `Thu Mar 9 11:42:26 2017 -0700`?

**Comment by Daniil145** [comment]
I delete "public" dir and run ./install_frontend.sh 6 hours ago

**Comment by RickCarlino** [comment]
@Daniil145 What does your javascript console show when you're logged in?

**Comment by Daniil145** [comment]
> @RickCarlino I install new api version and i tested this tomorrow. and send you message result

**Comment by Daniil145** [comment]
heh i install new version api sequence good work. bot dont connect

**Comment by RickCarlino** [comment]
@Daniil145 Great! I would recommend upgrading to the latest FBOS (we just released new stuff on Friday).

If you still have issues, please open a new issue for the FarmBot OS repo.

**Comment by Daniil145** [comment]
![2017-03-13 15 53 09](https://cloud.githubusercontent.com/assets/20598279/23855054/401c7d80-0805-11e7-96fb-ef2b77aeea90.png)

Move on controls work. sequence errors

**Comment by Daniil145** [comment]
ok i click button Disconected and bot is synsed - work)

**Comment by RickCarlino** [comment]
@Daniil145 You probably need to re-flash your bot.

`data_update` is a new RPC method we added last week to help the bot know it needs to download new information from the API (for syncing purposes).

I assume what is happening is that the frontend is sending the new RPC command to the bot, but the bot is running an old version of the software that does not understand the command.

**Comment by Daniil145** [comment]
Farmbot_os or firmware arduino?

**Comment by Daniil145** [comment]
I updated for farmbot-rpi3-3.0.8-rc.6.img and receive this error every time

**Comment by RickCarlino** [comment]
@Daniil145 FarmBot OS would need the update.

This issue appears to no longer be related to sequences or the frontend. Please [raise an issue in FarmBot OS](https://github.com/FarmBot/farmbot_os/issues/new) so that @ConnorRigby can help solve the problem. It will also make it easier for people with the same problem to find it later by searching.
