### ISSUE TITLE
Request For Enhancement: flexible Camera selection 

### ISSUE THREAD

**Issue by bautze** [FarmBot/farmbot-web-frontend#195]
# Expected Behavior
Expect some button / drop down menu to change camera to my standard Raspberry camera. USB camera (webcam) works. I would really appreciate this feature as I would like to use this cam. 
# Actual Behavior
taking image does not work, no camera found

**Comment by gabrielburnworth** [comment]
We have added a Camera selection drop-down in the Device widget on the Devices page. In it you can select the Raspberry Pi Camera.
