### ISSUE TITLE
Request For Enhancement - Homing Feature

### ISSUE THREAD

**Issue by bautze** [FarmBot/farmbot-web-frontend#198]
# Expected Behavior
I would like the bot to drive to physical (0,0,0). Software (0,0,0) can be wrong, especially when setting up and installing Farmbot for the first time. I would like to have a button that drives to x_min, y_min, z_min and sets zero position via G-code. Speed should be adjustable. 

# Actual Behavior
The calibration feature sort of does this, however the outcome is seems rather odd to me. For each axis, it drives to min, drives to max and then stops at max. Software setting for this point is (0,0,0). In my configuration (no inverted endpoints, no inverted motors, no negatives allowed) it is then stuck there as driving to the actual physical 0 is forbidden as software thinks I am at 0. Solving this always requires fiddling around and is quite cumbersome.

1. Could you implement such a homing feature? Would really appreciate it ! 
2. How do you use the calibration feature? Am I doing something wrong ? 

Thanks for you time !

**Comment by RickCarlino** [comment]
Hi @bautze we've spotted some bugs on the calibration feature and have been working on it all this week.

Will keep you posted and sorry for the slow response (it's been a busy week for everyone on the software team).

**Comment by bautze** [comment]
Hi, thanks for the reply. Actually, I was thinking that such a homing feature would actually be nice to use with the sequence builder as well !

**Comment by bautze** [comment]
Well, I tried the Calibration button and the Home button, however it is still rather inconvenient. Calibration drives to min, then to max and then set 0 at max. This leaves my bot stuck at max and I have to allow negatives and manually drive it to physical 0. 
I would have expected the home button to drive to the minimum endstop and stay there, it however drives to software defined zero (which is usually wrong after booting the bot).

**Comment by RickCarlino** [comment]
@bautze We've revamped our homing button and added a "set zero" button for all axes. Hope that helps! Please let me know if you need anything else and we can re-open as needed.
