### ISSUE TITLE
./install_fronted error

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot-web-frontend#199]
[npm-debug.txt](https://github.com/FarmBot/farmbot-web-frontend/files/853043/npm-debug.txt)

ERROR in ./src/app.tsx
(49,3): error TS2322: Type '{ dispatch: Function; auth: AuthState | undefined; bot: BotState; logs: Log[]; }' is not assignable to type 'AppProps'.
  Property 'loaded' is missing in type '{ dispatch: Function; auth: AuthState | undefined; bot: BotState; logs: Log[]; }'.

ERROR in ./src/app.tsx
(61,23): error TS2339: Property 'sync' does not exist on type '{ children?: ReactNode; } & FixMePlease'.

ERROR in ./src/app.tsx
(69,33): error TS2339: Property 'sync' does not exist on type '{ children?: ReactNode; } & FixMePlease'.

ERROR in ./src/app.tsx
(71,7): error TS2324: Property 'logs' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<NavBar> & { children?: ReactNode; } & NavBarProps'.
Child extract-text-webpack-plugin:
                                   Asset     Size  Chunks             Chunk Names
    a28eb8d21c40d7b84130c19dc70a9071.eot  75.7 kB          [emitted]
    a560594116f17fcc7460c611a8cac87c.eot  77.6 kB          [emitted]
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ./~/css-loader!./~/@blueprintjs/core/dist/blueprint.css 177 kB {0} [built]
       [2] ./~/@blueprintjs/core/resources/icons/icons-16.eot 82 bytes {0} [built]
       [3] ./~/@blueprintjs/core/resources/icons/icons-20.eot 82 bytes {0} [built]
       [4] ./~/@blueprintjs/core/resources/icons/icons-16.ttf 101 kB {0} [built]
       [5] ./~/@blueprintjs/core/resources/icons/icons-16.woff 101 kB {0} [built]
       [6] ./~/@blueprintjs/core/resources/icons/icons-20.ttf 103 kB {0} [built]
       [7] ./~/@blueprintjs/core/resources/icons/icons-20.woff 103 kB {0} [built]
       [8] ./~/css-loader!./~/sass-loader!./src/css/_index.scss 42.7 kB {0} [built]

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/root/.nvm/versions/node/v6.10.0/bin/node" "/root/.nvm/versions/node/v6.10.0/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! farmbot-web-frontend@1.1.0 build: `node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the farmbot-web-frontend@1.1.0 build script 'node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the farmbot-web-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/webpack/bin/webpack.js --config tools/webpack.config.prd.js --display-error-details
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs farmbot-web-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls farmbot-web-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/farmbot_frontend/npm-debug.log

**Comment by RickCarlino** [comment]
@Daniil145 Sorry for slow response- it's been a busy week for us. We are doing a lot of refactoring around the code base to help with overall stability. Unfortunately, the `HEAD` of master is unstable. I think that is the problem you are seeing.

You have two options:

 1. You can wait a few more days while we fix the issue.
 2. You can `./install_frontend` using an older, more stable version of the frontend (instructions below)

you will need to add new code under line 8 of `install_frontend.sh`:

```
. .  . . . 
git clone https://github.com/farmbot/farmbot-web-frontend.git /tmp/farmbot_frontend
cd /tmp/farmbot_frontend
___YOU_MUST_ADD_NEW_CODE_HERE___
```

add this code under line 8:

````
git checkout -b temporary1 9c6bee83
```

I have not tried this, so please let me know if you require more assistance. If the `9c6bee83` commit does not work, here are some other commits you can try:

```
7153ba6f
2847b382
fb7d6985
01d44e5e
676893e5
cff77c3b
```

Once this next release goes out, things will be much more stable. Unfortunately, the codebase is unstable in the meantime while we move things around.

**Comment by RickCarlino** [comment]
@Daniil145 `./install_frontend.sh` should be pretty stable now.

**Comment by punit121** [comment]
@RickCarlino i gone through ./install_frontend.sh . the only thing this is doing is that cloning frontend repo. in temp folder and then copying its public folder to the public folder of  **Farmbot-Web-API**  . 

can i proceed like this ::
first clone the frontend repository then run the npm commands and then  finally copy its public folder to the public folder of   **Farmbot-Web-API** 

Waiting for your reply

**Comment by RickCarlino** [comment]
@punit121 I'm glad you were able to get it working. If you want to publish that as a script to a new Github repo, I would be happy to link to it in the documentation. It would be a great way to help others in your situation.

Unfortunately, Windows support isn't a big priority for me right now with given time limitations. I do not own a Windows machine to test off of, and all of our software (eg: FarmBot OS, and the production server) run on *nix machines.

My recomendation if you hit any other issues on Windows would be to either purchase low cost server hosting at [Vultr](www.vultr.com) or [Digital Ocean](www.digitalocean.com), use a virtual machine or provision a Linux server locally on low cost hardware such as a Raspberry Pi.

**Comment by punit121** [comment]
@RickCarlino Thanks a lot for your help . 
can you help me with following error i'm facing :
i'm running the following jquery code after running the rail server for getting API Token : 
but i'm getting ** Failed to load resource: the server responded with a status of 500 (Internal Server Error) **  
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script>
$.ajax({
    url: "http://localhost:3000/api/tokens",
    type: "POST",
    data: JSON.stringify({user: {email: 'admin@admin.com', password: 'password123'}}),
    contentType: "application/json",
    success: function (data) {
                 // You can now use your token:
                 var MY_SHINY_TOKEN = data.token.encoded;
					console.log("hello World!");
					console.log(MY_SHINY_TOKEN);	
			 }
});
</script>

Please tell me which ENV variables i'll have to set for running this app on localhost, 
**  Also please specify where to use API Token (in which file)  (do we need to set this in Farmbot-web-frontend or Farmbot-web-API)  ** 
(do i need raspberry pi also for running this locally ? )

  
Also i'm getting the following once opening http://localhost:3000/app/login 
** Farmbot failed to build front end assets during deployment. **

Please elaborate me everything about all the errors i'm facing 

Waiting for your reply ..

**Comment by RickCarlino** [comment]
@punit121 A few things:

1. You don't need to use API tokens for anything unless you are trying to build a new software application for FarmBot.
2. All of the the ENV vars (and explanations) can be found [here](https://github.com/FarmBot/Farmbot-Web-API/blob/master/config/application.example.yml)
3. You don't need a Raspberry Pi if you don't have a bot or are just testing things out locally.
4. Please create a new issue [here](https://github.com/FarmBot/Farmbot-Web-API/issues/new?title=Farmbot%20failed%20to%20build%20front%20end%20assets%20during%20deployment) for support with the front end assets error. Please copy/paste the full error message.
