### ISSUE TITLE
Request For Enhancement: Export / Import Feature

### ISSUE THREAD

**Issue by bautze** [FarmBot/farmbot-web-frontend#203]
Programming sequences is a time-consuming task. We would like to have a feature to export, share and import sequences. This helps developing the community faster and is also useful for backup. I would appreciate a standard plain-text format like json for the export. Nothing special, just something that works plain and simple.

**Comment by RickCarlino** [comment]
@bautze That's a great idea and it is already on our road map to add sequence sharing.

The other good news is that the sequences are already JSON documents under the hood. The sequence builder (and all bot commands) use an abstract syntax tree structure internally referred to as "Celery Script" . The format of these JSON nodes is [outlined here](https://github.com/FarmBot/farmbot-js/blob/master/dist/corpus.d.ts), but we have not yet formally written documentation on the structure of Celery Script nodes. You can see the structure of your own sequences by downloading them from the `api/sequences/` endpoint of the API ([here's how to create an API token](https://github.com/FarmBot/Farmbot-Web-API#generating-an-api-token))

If you have a specific use case for software that would benefit from interfacing with Celery Script, I could write some developer docs about it. Please let me know if that's the case.

**Comment by bautze** [comment]
That sounds great ! The format from your link looks really good, this is sufficient for me, I will look into it once I am live in production. I have a few ideas in mind what to do with it, however I think that there are currently other more important issues to solve. I'll keep you posted. Thanks
