### ISSUE TITLE
Impossible to set Hardware Configuration

### ISSUE THREAD

**Issue by bautze** [FarmBot/farmbot-web-frontend#204]
Example: Setting new values for X AXIS - MAX SPEED (MM/S) to a new value triggers the log: 
"is updating movement_max_spd_x: 800"
however the new values are not saved. Tried several times, the behavior is reproducible. FarmbotOS 3.1.0

**Comment by RickCarlino** [comment]
@bautze Thanks for the heads up. We will be working on this issue today, along with many other fixes for that panel. I will keep this issue open for now until the fixes are deployed.

**Comment by bautze** [comment]
:-)

**Comment by RickCarlino** [comment]
@bautze This has been fixed, please let me know if you require any further assistance, and thanks again for bringing it to our attention.
