### ISSUE TITLE
Stuck in software loop

### ISSUE THREAD

**Issue by bautze** [FarmBot/farmbot-web-frontend#206]
Version 3.1.2 
Farmbot is stuck in a loop (see below). I have installed latest OS version, Farmbot was working, stopped working after sending toggle of endstop on/off.
If you haven't had this issue beforehand, I could offer my bot as testing device. 

[FILTERED]
6:23 pm
summer-fire-798 is starting serial services
6:23 pm
setting previous mcu commands.
6:22 pm
[FILTERED]
6:22 pm
summer-fire-798 is starting serial services
6:22 pm
setting previous mcu commands.
6:21 pm
[FILTERED]
6:21 pm
summer-fire-798 is starting serial services
6:21 pm
setting previous mcu commands.
6:19 pm
[FILTERED]

**Comment by RickCarlino** [comment]
Thanks for letting us know, @bautze . We will take a look. I have a suspicion it might be related to [farmbot_os/292](https://github.com/FarmBot/farmbot_os/issues/292).

CC: @ConnorRigby

**Comment by ConnorRigby** [comment]
This happens when farmbot can't communicate with it's Arduino. Have you tried a reboot?

**Comment by AscendFB** [comment]
I also had this issue a few times. I felt like its coming everytime I try to change hardware parameters. Even after many reboots it came up again.

**Comment by ConnorRigby** [comment]
The hardware parameter save button can cause the bot to be pretty unstable the way it is right now. We have a fix for that in our staging environments that should fix it hopefully. 

any steps i can do to reproduce the loop you guys are seeing?

**Comment by AscendFB** [comment]
Tried like 30min to reproduce, no success yet. My Farmbot was unplugged over night, don't know what could have changed or if its just rare.

**Comment by bautze** [comment]
Yes I tried reboot, did not change anything. To reproduce, I would recommend clean install of latest version, then doing first-time set-up, moving a bit around, sending toggle request to device config and that did the trick for me. The bot then thinks it is at -1, -1, -1. In case it is related, I should maybe wait for new fix and then try if I see it again.

**Comment by bautze** [comment]
Something that might be helpful is if logging level would be higher as default setting for the moment, this way we could maybe provide more info.

**Comment by ConnorRigby** [comment]
Toggles shouldnt cause it i wouldnt think. 
This problem comes from the bot not being able to negotiate communications with the arduino firmware.

**Comment by bautze** [comment]
Sounds reasonable as toggling not working would be a consequence of the communication issue.

**Comment by AscendFB** [comment]
Is is working for you right now @bautze ?
My setup seems to work fine, saving hardware parameters are still bugged, of course, but It does no more stuck in loops.

**Comment by bautze** [comment]
No, still not working, what did you do to make it work?

**Comment by AscendFB** [comment]
Last thing I did yesterday, was flashing to an older OS Version, and then back to V3.1.2. When it was done I immediately shut it down. Now starting almost 24h later I have no problems anymore. Cant imagine this would help.

**Comment by bautze** [comment]
I did a clean install of V3.1.3, it did not accept my configuration, I pressed the reset button on the ramps, then the configuration went through and Farmbot booted. Afterwards, all device hardware configuration was gone, toggle buttons are yellow, impossible to set devices. Log output:
8:05 pm [FILTERED]
8:05 pm reading all mcu params.
8:05 pm (red) [FILTERED]
8:04 pm apiculate-glitter-455 is starting serial services
8:04 pm apiculate-glitter-455 is synced!

1. Would it help for debugging if I used staging.farmbot.io ? (Do you have a higher loglevel there?)
2. What does [FILTERED] stand for ?

Sorry for pushing.

**Comment by ConnorRigby** [comment]
`[FILTERED]` Just means it might be a sensitive message, so we dont push it to the logs for security purposes.

Pressing the reset button on the ramps board is usually a pretty _bad_ idea, and can cause the bot and ramps to be out of sync pretty bad. 

When you _dont_ hit the reset button and boot up your bot, are you able to use toggle buttons on the settings? If so you have a good connection between your arduino and bot. The fix for the other (non toggles) is in development right now and should be ready really soon. 

https://staging.farmbot.io does not have anything helpful for end users and we don't suggest using it unless you are a developer.

**Comment by bautze** [comment]
I pressed, since after flashing latest OS on SD-card, I did not manage to get out of configuration (192.168.24.1) and my bot did not connect to the webapp. This was the last option I saw and apparently afterwards, it connected. I understand that this is usually a bad idea.
When my bot is up and running, I do not manage to toggle buttons. To me this seems odd, as I would expect it to work after a fresh reinstall of the OS (via dd). Everything is connected just the way it was when it last worked (V3.1.1).
Do you know, how I could check (maybe on the pi via ssh) if my arduino is responding properly?

**Comment by bautze** [comment]
Fixed by Version 3.1.4
