### ISSUE TITLE
Feedback for Version 3.1.4

### ISSUE THREAD

**Issue by bautze** [FarmBot/farmbot-web-frontend#209]
Version 3.1.4 is a big step forward, thanks for update and the new features. Most of them are working properly, I will leave the issues that I have found today here:

1. Unhandled messages:
1.1 7:50: reading all mcu params
7:51:"Encountered an error handling: R21 P12 Q0: %MatchError{term: [""]}
1.2.Unhandled message: "F21 P0 Q2 V60 Q0"
1.3. Unhandled Message: "Z6150 Q45"
1.4 Unhandled Message: "0 Z6150 Q0"

2. After almost every manual move, I get the red message box "Farmbot didn't get the request...", however movement just worked fine. 

3. The behavior when pressing for example "Home x" is not always 100% the same. Sometimes, it moves x-axis AND z-axis at the same time! Unsure how to reproduce, to me, I cannot reproduce, it happens randomly.

4. Impossible to toggle: "Always Power Motors".
(Other toggles are working just fine) 

5. Questions:
What does the message: arduino says: V1 | V2 mean?

**Comment by TimEvWw** [comment]
V1 and V2 is my mistake. Those were debugging messages that were not
removed. That's already fixed for the new version.

**Comment by mdingena** [comment]
My feedback on calibration (I know encoders are in alpha):

* Calibrating Y-Axis
* Steps/mm = 5
* Encoder Scaling = 100
* My motors are from Genesis pre-order kit
* Enable Encoders `YES`
* Invert Encoders `YES`

Y-Axis will not calibrate without "Invert Encoders". It moves 10 mm both ways and stops. When this option is on, it actually moved to both ends of the gantry and stops.

However, after stopping, its position is -8420. My gantry isn't 8 meters long, so I think calibration also changes some settings like steps per mm or so.
