### ISSUE TITLE
webcam placeholder image overflow

### ISSUE THREAD

**Issue by creimers** [FarmBot/farmbot-web-frontend#211]
# Expected Behavior
Image no wider than its parent container.

# Actual Behavior
<img width="1920" alt="bildschirmfoto 2017-05-06 um 09 31 27" src="https://cloud.githubusercontent.com/assets/6090492/25770793/703678ae-323f-11e7-93c7-9ae853362566.png">

# Steps to Reproduce
Chrome  57.0.2987 on Mac, log into my.farmbot.com, 'Controls' tab.

**Comment by RickCarlino** [comment]
@creimers Yep, we just spotted this one last week also. Thanks for the heads up. Will close this issue when it is resolved.
