### ISSUE TITLE
Frontend if statement in sequences drop down listing cut

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/farmbot-web-frontend#215]
# Expected Behavior
to see all listings in the drop down menu
# Actual Behavior
listing is cut
# Steps to Reproduce
select drop down menu as seen in screen shot

Browser: Chrome on Mac Version: 58.0.3029.110 (64-bit)
Frontend: 0C6C947
![bildschirmfoto 2017-05-29 um 20 40 16](https://cloud.githubusercontent.com/assets/28235189/26562671/b80138ea-44c8-11e7-8083-ab64421b0e4a.png)

**Comment by RickCarlino** [comment]
@Klimbim1 I just saw this one crop up recently. I have added this to our internal TODO. Thanks for the headsup. I will close this issue when the fix is deployed.
