### ISSUE TITLE
Farmbot didn´t get that...

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/farmbot-web-frontend#217]
That is the farmbotters most dislike message I guess :)

Got it today so many times... it is not a problem of my wifi coverage, it shouldn´t be a problem of the browser as I used Firefox and Chrome on an iPhone. It is just annoying if you need to reload the page, do it again etc... the whole frontend seems to very unresponsive (read = slow)...

Why do you need to wait that long after taking a picture?

Cheers

**Comment by RickCarlino** [comment]
@Klimbim1 Can I see your javascript console when the error occurs? Other relevant information would be:

 * MQTT logs (if you are self hosting)
 * Bot logs (if any)
 * Version of the frontend you are running.

**Comment by Klimbim1** [comment]
Hey @RickCarlino that was yesterday, unfortunately I was too slow and couldn't capture the java error with the message Farmbot didn't get that. After a reload of the page everything is normal again... 
![bildschirmfoto 2017-06-13 um 19 41 31](https://user-images.githubusercontent.com/28235189/27096205-8a8c9946-5070-11e7-9b60-fb6dfc99602e.png)
Current version is 0C6C947 with your servers...
