### ISSUE TITLE
Add 'Layers' Button/Menu

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-web-frontend#3]
This button should open up a small menu that allows the user to toggle the display of different elements in the map view. Elements that should be toggle-able:
* Plants
* Plant Groups
* Zones
* Grid
* FarmBot
* Data sets (pH, Moisture, Temperature, etc)

Obviously we can only currently toggle Plant elements, but as we add more things it will be nice to be able to hide them.

**Comment by RickCarlino** [comment]
Noted! Will add it to the stack when I get home Friday.

**Comment by RickCarlino** [comment]
Closing inactive issue.
