### ISSUE TITLE
Registration doesn't auto-login the user (oops)

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot-web-frontend#50]
# How to Replicate

1. Go to production.
2. Sign up.
3. Watch in horror as your account is created but NOT automatically logged in.

**Comment by roryaronson** [comment]
Haha in this vein, is it possible for the user to stay logged in longer and it auto-load the app? Everytime I open a web app tab I have to click "Login or Create Account" from the splash page, and then click "Login".

If I already had an account and was logged in, it would be nice if going to my.farmbot.io took me straight to the manual control page.

**Comment by RickCarlino** [comment]
Resolved.
