### ISSUE TITLE
Execute Sequence does not work without saving directly after adding Steps

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-web-frontend#58]
Rick, remember how the sequence didn't execute when I first made it but hadn't yet saved it?

Its not an issue with having to save at least once, its an issue with having to save after any additional Steps are added to the Sequence. I think its because when Steps are added but not saved, they don't yet have an `ID`.

## When adding the first Step to a brand new Sequence
This is what is sent to the pi before saving:
`{"params":{"color":"gray","name":"New Sequence","steps":[{"message_type":"move_absolute","command":{"x":"3000"}}],"dirty":true},"method":"exec_sequence","id":"23f39978-1100-4b28-91ba-439f0e91bccf"}`

This is what is sent to the pi after saving:
`{"params":{"_id":"572927dacd3204000800005a","name":"New Sequence","color":"gray","steps":[{"_id":"572927dacd3204000800005b","command":{"x":"3000"},"message_type":"move_absolute","position":0}]},"method":"exec_sequence","id":"49df0c2e-327e-4907-9e3f-750c70677429"}`

## When adding more Steps to an already saved before Sequence
This is what is sent to the pi before saving:
`{"params":{"_id":"572927dacd3204000800005a","name":"New Sequence","color":"gray","steps":[{"_id":"5729280bcd3204000800005d","command":{"x":"0"},"message_type":"move_absolute","position":0}],"dirty":true},"method":"exec_sequence","id":"18b569c0-f5a1-4920-a948-eb3bad1aceef"}`

This is what is sent to the pi after saving:
`{"params":{"_id":"572927dacd3204000800005a","name":"New Sequence","color":"gray","steps":[{"_id":"5729280bcd3204000800005d","command":{"x":"0"},"message_type":"move_absolute","position":0},{"message_type":"move_absolute","command":{"x":"3000"}}],"dirty":true},"method":"exec_sequence","id":"aa8a07df-39ab-43fc-8906-ceb630d09f44"}`

**Comment by RickCarlino** [comment]
Resolved
