### ISSUE TITLE
Not work disigner page

### ISSUE THREAD

**Issue by drdim** [FarmBot/farmbot-web-frontend#67]
my.farmbot.io.js:77 Uncaught TypeError: Cannot read property 'planting_area' of undefined

**Comment by RickCarlino** [comment]
Greetings! We're aware of this issue. Right now, our big focus is the regimen scheduler and sequeunce editor. It will be a while before this one gets fixed.

Please stop by our [Gitter chat](https://gitter.im/FarmBot/chat) if you need any other help getting set up. There are quite a few of us in their during the day.
