### ISSUE TITLE
Can't edit device name

### ISSUE THREAD

**Issue by drdim** [FarmBot/farmbot-web-frontend#68]
On page /app/dashboard/devices

Can't edit FARMBOT NAME

**Comment by roryaronson** [comment]
Hey @drdim thanks for trying out our software and filing some bug reports. All of our codebases are still in an alpha/beta stage. So many features don't yet work.

What is working is the manual controls, updating (most) of the device settings, and sequence building. Our next big milestone is regimens.

Are you interested in helping out with the development at all?
