### ISSUE TITLE
Breakup plant_inventory.js

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-web-frontend#8]
I think it would be easier to deal with the farm designer's left panel if the code in `plant_inventory.js` was broken up into different files such as: `plant_inventory.js`, `group_inventory.js`, and `zone_inventory.js`

What do you think @RickCarlino?

**Comment by RickCarlino** [comment]
Agreed. Was just lumped together while prototyping. I can start separating it out on Monday, but feel free to break it apart and submit a PR if you have time. I think there are a couple other files that haven't been separated out yet, also (can't remeber file names off the top of my head).

Typically, I like to keep one class per file, and name the file after the class it defines.

**Comment by roryaronson** [comment]
Cool. I'll wait for you to do it on Monday because there is some logic in there with the routing and such that I don't want to break. Its a little over my head!

**Comment by roryaronson** [comment]
PS, the app is looking pretty refined! :)

**Comment by RickCarlino** [comment]
Thanks! It's coming along bit by bit.

**Comment by roryaronson** [comment]
Ended up figuring it out for the most part!

Lots of styling ready to be reviewed and merged when you get a chance :)
