### ISSUE TITLE
crowdin.com

### ISSUE THREAD

**Issue by migarol** [FarmBot/farmbot-web-frontend#83]
Add a collaborative page to translate, i can translate to spanish

**Comment by RickCarlino** [comment]
@migarol Great idea! We could definitely support i18n for this project.

I am not familiar with GNU Gettext or crowdin.com so I will need to look into this one more, but I definitly agree that English shouldn't be the only option.

Leaving this issue open for now.

**Comment by migarol** [comment]
Great, let me know if you need help, i can help you out with setting it up and doing some translation to spanish.

**Comment by rmariuzzo** [comment]
I can also help!

**Comment by RickCarlino** [comment]
Greetings folks-

I am going to close this one as we have i18n on the roadmap but won't be implementing anything for a while.
