### ISSUE TITLE
Default login info?

### ISSUE THREAD

**Issue by ShaggyDude** [FarmBot/farmbot-web-frontend#84]
Is there a test login? I'm looking for it but can't find it..

**Comment by roryaronson** [comment]
I don't believe there is. You can just make a new username/password though.

**Comment by ShaggyDude** [comment]
I get an error trying this from localhost on a mac. Should it work locally?

**Comment by RickCarlino** [comment]
Are you running an API server locally? If not, you can create an account on the [staging server](http://staging.farmbot.io) and point your local client to that. Please let me know if that doesn't work and we can take it from there. Thanks for checking out the repo!

**Comment by ShaggyDude** [comment]
Ahh, no I need to set up the API server.

**Comment by RickCarlino** [comment]
@ShaggyDude You don't need to per-se if you are only interested in working on the frontend. Pointing the frontend client at the staging server should be good enough in most cases. Please let me know if that fixes your issue. Closing this issue for now, can re-open if you still need help.
