### ISSUE TITLE
Is there a roadmap for this project

### ISSUE THREAD

**Issue by ivanmayes** [FarmBot/farmbot-web-frontend#87]
Curious if there is a roadmap for the web software side of this project.  I'm very passionate about this project and would love to contribute to the web frontend / api side of things, but would prefer to spend time working towards something that is already in the near term vision for the web functionality.

**Comment by roryaronson** [comment]
Thanks for asking! We don't have too much of a roadmap (its mostly in mine and @RickCarlino's heads). But what we have been doing is using Trello boards for 2-3 week sprints. Something we can start doing though is posting a link to these trello boards in an issue here on GitHub, or start using the issue tracker here more consistently. Have you got the codebase working locally yet? Do you have any particular feature you would like to help us out with?

**Comment by RickCarlino** [comment]
@ivanmayes Thanks for checking out the project. If you're looking for general areas that need help, here are a few that would be useful and also help give you a better taste of the project architecture:

 * This is one of the only repos that doesn't have a good test suite. Our coverage is basically 0 right now and I would like to get it higher than that.
* We transitioned from ES6 to Typescript a few months ago. There are a bunch of `implicit "any"` types that could use anotation, as well as adding TSDoc comments to functions and classes (might be a good way to learn the project in the process)
 * If you search the project for the word `TODO` or `HACK` you will find a bunch of technical debt. I am more than happy to help you tackle those and answer questions if you have any.

Let us know if you need help setting up.

**Comment by clubleveljoe** [comment]
I'm more of a Ruby guy than a JS guy... Could you give an overview of what you need help with on the API side? I'm happy to open up a ticket like this one over there if it would be helpful.

**Comment by RickCarlino** [comment]
@clubleveljoe I would prefer to keep API discussions out of this repo, but to answer your question, there's not too much going on with the API right now. It's our most stable piece of software and it rarely changes. There might be some `TODO` items in the codebase still, though if you want to take a look. If you have any questions, let me know by raising an issue in the API repo.
