### ISSUE TITLE
Local Language Support

### ISSUE THREAD

**Issue by nataraajc** [FarmBot/farmbot-web-frontend#88]
Hi, I would like to check if we have local language support. Do we have any plan/support for the same? If we already have design for local languages where to start with?

**Comment by RickCarlino** [comment]
@nataraajc It's scheduled, but not started. We we're considering using Mozilla's `L20n` library, but it doesn't play nicely with NPM (or at least, it seems that way for us).

Do you have any preferences for i18n libraries that support React.js?
