### ISSUE TITLE
Issues registering for an account.

### ISSUE THREAD

**Issue by JefHinton** [FarmBot/farmbot-web-frontend#89]
<img width="485" alt="screen shot 2016-07-26 at 7 51 02 pm" src="https://cloud.githubusercontent.com/assets/19696231/17160417/6ed9e02c-536a-11e6-8930-ea7f0d56e5ef.png">

I got all the way to the 
http://localhost:8080/app/login Part.

Any Idea on where I go to set up an account?

**Comment by RickCarlino** [comment]
What message did you see after submitting the `Create an Account` form? Could have sworn that was working. My guess is that you aren't running an API locally and it tried doing a POST to your machine?

**Comment by JefHinton** [comment]
Yea, it is running a post to my machine. Really what I think I need is a link to the register an account webpage.

**Comment by RickCarlino** [comment]
A little background:

Farmbot frontend works a lot an IRC chat client (or FTP client for that matter). You specify the URL and it connects to that server. In your screen shot, you are pointing at `//localhost`, but you aren't actually running a server on `localhost`.

Can you try this for me?

1. Restart the frontend.
2. Change `//localhost:3000` to `//my.farmbot.io`
3. Try to register for an account
4. Let me know if it works and, if not, what errors are shown in the Javascript console (please copy/paste the full message).

I would check it out myself but I am on the road. Please let me know what you find and we can take it from there. I would consider this a bug if it doesn't work. I can take a look within the next few days when my schedule calms down.
