### ISSUE TITLE
Render a grid on the garden map

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-web-frontend#9]
I accomplished this with a CSS trick, but it would probably be better to use React SVGs to render it? That way it would be feasible to adjust the grid for english vs metric units, different spacing, display on/off, etc.
![capture](https://cloud.githubusercontent.com/assets/5524043/11460181/20bf1f86-969d-11e5-9f2b-db98cd790218.JPG)

**Comment by RickCarlino** [comment]
I think the SVG idea might be more complex, but won't know for sure until
we try. Looks awesome from a visual standpoint, definitely great to see.
Will be back at it on Monday for both PRs.

**Comment by roryaronson** [comment]
Cool, I'm going through and adding a bunch of features that we can keep track of/work on. Talk to you on Monday!

**Comment by RickCarlino** [comment]
Closing inactive issue.
