### ISSUE TITLE
Routed to /login

### ISSUE THREAD

**Issue by clubleveljoe** [FarmBot/farmbot-web-frontend#90]
I run npm start and can access the site at http://localhost:8080 but am routed to /login instead of /app/login by default.

**Comment by RickCarlino** [comment]
I'm having trouble replicating on local. Which OS / browser are you running?

@roryaronson Have you experienced this recently?

**Comment by roryaronson** [comment]
@RickCarlino I haven't touched my local setup since the launch campaign, so I don't know, but I don't think so?

**Comment by RickCarlino** [comment]
Closing until we get more information.

**Comment by davetom13** [comment]
@RickCarlino I remember seeing this github issue when it came in. I recently updated my Pi with the latest build which seems to be stable, except for this issue. On Mac OSX chrome :8080/app/login works fine, but on IOS when you goto :8080/app/login it redirects to :8080/login and the page remains grayed out. It appears to be a mobile redirect issue. Not sure if this is the same as the OP, but figured I would throw it out to help diagnose. I haven't had a chance to look at the code to see where the problem may be yet.
