### ISSUE TITLE
Custom API Endpoint Error

### ISSUE THREAD

**Issue by clubleveljoe** [FarmBot/farmbot-web-frontend#91]
When logging into the front-end I have specified my server URL to point to http://projectname.nitrousapp.com:3000 and I can log-in fine.

However all the requests to the API after logging in are routed to http://projectname.nitrousapp.com:3000//app/resource and result in errors as the API attempts to redirect them.

Any idea on the extra trailing slash?

**Comment by RickCarlino** [comment]
@clubleveljoe Could you show me the exact resources that are erroring out? That will help me see if an extra `/` slipped into the codebase somewhere. I've seen this issue before on some machines.

**Comment by RickCarlino** [comment]
I think I may have a possible fix for this one. Was able to reproduce on last staging deploy. Details to follow.
