### ISSUE TITLE
version bug in package.json?

### ISSUE THREAD

**Issue by creimers** [FarmBot/farmbot-web-frontend#93]
Following "Up and Running" from the README, I get:

```
npm ERR! No compatible version found: farmbot@1.3.0
npm ERR! Valid install targets:
npm ERR! 1.2.1, 1.2.0, 1.1.0, 1.0.0, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.1
```

**Comment by RickCarlino** [comment]
@creimers Whoops! That's a bug on something I'm working on *right now*. Will it now. As a side note, if you need to use a stable version, consider looking at a tagged release. If you're just looking around and wanted to see the "edge" version, you're in the right spot.

**Comment by RickCarlino** [comment]
Just downgraded `farmbot` version. If you `git pull` latest, `npm uninstall farmbot` and `npm install` you should be good to go.

You can safely ignore the red warning messages, as that's something I am working on today. Master branch is typically unstable, so it might be best to use a [release version](https://github.com/FarmBot/farmbot-web-frontend/releases) if you need something more stable.

**Comment by RickCarlino** [comment]
Closing issue for now, but feel free to keep the discussion going if that doesn't help.
